server:
  port: 8081
  servlet:
    context-path: ""


name: dev environment
age: 27
people: "name:${name} age:${age}"
spring:
  datasource:
    url: jdbc:mysql:localhost:3306/test
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
    mode: LEGACYHTML5


